version: 2
updates:
  # Base image updates for main
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels: ["dependencies"]
    target-branch: "main"
    
  # GitHub Actions updates for main
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "actions"
    labels: ["dependencies"]
    target-branch: "main"

  # Base image updates for lts
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels: ["dependencies"]
    target-branch: "lts"

  # GitHub Actions updates for lts
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "actions"
    labels: ["dependencies"]
    target-branch: "lts"
