---
name: Build image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 05 * * *'  # 05:05am UTC everyday
  push:
    branches:
      - main
      - lts
      - test
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_DESC: "Atomic Kitten"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          # Set branch-based tags
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "DEFAULT_TAG=latest" >> ${GITHUB_ENV}
          elif [ "${GITHUB_REF##*/}" = "lts" ]; then
            echo "DEFAULT_TAG=lts" >> ${GITHUB_ENV}
          elif [ "${GITHUB_REF##*/}" = "test" ]; then
            echo "DEFAULT_TAG=test" >> ${GITHUB_ENV}
          else
            echo "DEFAULT_TAG=dev" >> ${GITHUB_ENV}
          fi
          # Set date tag
          echo "DATE_TAG=$(date -u +%Y%m%d)" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.DEFAULT_TAG }}
            ${{ env.DEFAULT_TAG }}.${{ env.DATE_TAG }}
            ${{ env.DATE_TAG }}
          oci: false
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            IMAGE_REGISTRY=${{ env.IMAGE_REGISTRY }}

      # Login and push steps
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        if: github.event_name != 'pull_request'
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.DEFAULT_TAG }}
            ${{ env.DEFAULT_TAG }}.${{ env.DATE_TAG }}
            ${{ env.DATE_TAG }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          for tag in ${{ env.DEFAULT_TAG }} ${{ env.DEFAULT_TAG }}.${{ env.DATE_TAG }} ${{ env.DATE_TAG }}; do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
          done
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
